### ISSUE TITLE
Recover Files vs. Version - different naming in context menu and synch view

### ISSUE THREAD

**Issue by patwinz** [Hive2Hive/PeerBox#108]
In the synchronization view, the context menu item is labeled as "Recover File" while in the Shell context menu it says "Versions" - we might want to have the same name in both locations. I think "Recover Files" sounds more intuitive.

**Comment by albrechta** [comment]
I changed the commands to: 
- Hard Delete
- Recover File Version
- Share Folder

It should be easier to understand each command now.
