### ISSUE TITLE
Simplify adding bootstrap nodes

### ISSUE THREAD

**Issue by nicoruti** [Hive2Hive/PeerBox#109]
In the settings --> Network tab, I tried to add own bootstrap nodes. It is possible to hit the 'Add' button ad then enter any IP address / domain name and then <strong>hit enter</strong>.
If enter is not pressed, but instead another button ('add', 'save', 'up' or 'down') is pressed, the just entered bootstrap node is not saved.

**Comment by albrechta** [comment]
Unfortunately, this is just how the control works and the reason is probably that you can abort editing without accidentally change a value. 
However, I did change it and switched to simple input dialogs which allow entering or editing the addresses.
