### ISSUE TITLE
Bind user name to peerbox path

### ISSUE THREAD

**Issue by raute** [Hive2Hive/PeerBox#72]
In the login-view, the user is able to change its root path easily. This allows him to select a completely different path (e.g. from another user) and generates a messy state

**Comment by albrechta** [comment]
every user has a config file where the name of the file is the hash of the username (i.e. hash(username).conf). same holds for the profile database.
If config file exists: path is selected as written in the file. User cannot change path.
If no config file exists: user can select path (or can use proposed default path).
